# -*- coding: utf-8 -*-
"""scheduler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-zJ6PHS5JaiNj4TLsoCsY4KytMQONYn
"""

import streamlit as st
import pandas as pd

# ---------------- DATOS ---------------- #
data = {
    "GRUPO": [
        "PHLCFI-401 GAM", "PHLCFI-402 GAM", "PHLCFI-403 GAM",
        "PHLCFI-404 GAM", "PHLCFI-714 UST"
    ],
    "ASIGNATURA": [
        "INVESTIGACIÓN DE OPERACIONES", "INVESTIGACIÓN DE OPERACIONES", "INVESTIGACIÓN DE OPERACIONES",
        "INVESTIGACIÓN DE OPERACIONES", "SIMULACIÓN BURSÁTIL Y FINANCIERA AVANZADA EN FINANZAS"
    ],
    "LUNES": ["", "", "", "7-9", ""],
    "MARTES": ["", "", "", "", ""],
    "MIÉRCOLES": ["", "", "", "", ""],
    "JUEVES": ["", "", "", "", ""],
    "VIERNES": ["", "", "", "", ""],
    "SÁBADO": ["", "", "", "", ""],
    "AULA": ["C-103", "C-104", "C-105", "A-CHAL", "A-111"],
    "INDICADOR": ["P-LM/C-JS", "P-LM/C-JS", "P-JS/C-LM", "P-JS/C-LM", "P-JS/C-LM"]
}

df = pd.DataFrame(data)

# ---------------- APP ---------------- #
st.set_page_config(page_title="Horario de Clases", layout="wide")
st.title("📅 Horario de Clases")

# Mostrar toda la tabla
st.subheader("Tabla Completa")
st.dataframe(df)

# Filtrar por grupo
grupo = st.selectbox("Selecciona un grupo:", df["GRUPO"].unique())
st.subheader(f"Horario del grupo {grupo}")
st.table(df[df["GRUPO"] == grupo].drop(columns=["GRUPO", "ASIGNATURA", "AULA", "INDICADOR"]))


# --- Personalización de diseño ---
st.markdown("""
<style>
    .stApp {
        background-color: #00FF00;
    }
    .css-1d391kg {
        color: #faf7f8;
    }
</style>
""", unsafe_allow_html=True)
