# -*- coding: utf-8 -*-
"""scheduler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-zJ6PHS5JaiNj4TLsoCsY4KytMQONYn
"""

import streamlit as st
import pandas as pd

# ---------------- DATOS ---------------- #
data = {
    "GRUPO": [
        "PHLCFI-403 COY", "PHLCFI-406 COY", "PHLCFI-409 GAM",
        "PHLCFI-304 UST", "PHLCFI-404 UST"
    ],
    "ASIGNATURA": [
        "FINANZAS BÁSICAS", "INVESTIGACIÓN DE OPERACIONES", "LABORATORIO DE INNOVACIÓN SOCIAL",
        "PROBABILIDAD", "INVESTIGACIÓN DE OPERACIONES"
    ],
    "LUNES": ["13-15", "", "", "9-11 (ON LINE)", "7-9 (ON LINE)"],
    "MARTES": ["", "", "", "", ""],
    "MIÉRCOLES": ["15-17", "", "13-15 (ON LINE)", "", ""],
    "JUEVES": ["13-15 (ON LINE)", "17-19 (ON LINE)", "", "9-11", "7-9"],
    "VIERNES": ["", "", "", "", ""],
    "SÁBADO": ["", "", "13-15", "", ""],
    "AULA": ["A-014", "A-011", "A-ZAC", "A-112", "A-113"],
    "INDICADOR": ["P-LM/C-JS", "P-LM/C-JS", "P-JS/C-LM", "P-JS/C-LM", "P-JS/C-LM"]
}

df = pd.DataFrame(data)

# ---------------- APP ---------------- #
st.set_page_config(page_title="Horario de Clases", layout="wide")
st.title("📅 Horario de Clases")
st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=300)

# Mostrar toda la tabla
st.subheader("Tabla Completa")
st.dataframe(df)

# Filtrar por grupo
grupo = st.selectbox("Selecciona un grupo:", df["GRUPO"].unique())
st.subheader(f"Horario del grupo {grupo}")
st.table(df[df["GRUPO"] == grupo].drop(columns=["GRUPO", "ASIGNATURA", "AULA", "INDICADOR"]))


# --- Personalización de diseño ---
st.markdown("""
<style>
    .stApp {
        background-color: #00FF00;
    }
    .css-1d391kg {
        color: #faf7f8;
    }
</style>
""", unsafe_allow_html=True)
